spring:
  application:
    name: parkingLot
    version: 1.0.0

  datasource:
    url: jdbc:postgresql://localhost:5432/parking-lot
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # Optional: configure Flyway
    flyway:
      enabled: true
      locations: classpath:db/migration

Vehicle:
  type:
    Car:
      hourlyCharges: 100
    HANDICAPPED:
      hourlyCharges: 100
    LARGE:
      hourlyCharges: 100
    MOTORBIKE:
      hourlyCharges: 100
    ELECTRIC:
      hourlyCharges: 100
    EBIKE:
      hourlyCharges: 100







